# COMANDO: .help (Ayuda compacta)
- alias: "MeshCore Bot: Ayuda"
  trigger:
    - platform: event
      event_type: meshcore_raw_event
  condition:
    - condition: template
      value_template: "{{ '.help' in trigger.event.data.payload.decrypted.text | lower }}"
  action:
    - delay: "00:00:01"
    - action: meshcore.send_channel_message
      data:
        channel_idx: 6
        message: "[Bot] .ping o .test para (Ruta y latencia), .quien [byte] (Nombre y última escucha). "


# COMANDO: .test (Reporte técnico de señal)
- alias: "MeshCore Bot: Test Técnico"
  trigger:
    - platform: event
      event_type: meshcore_raw_event
  condition:
    - condition: template
      value_template: "{{ '.test' in trigger.event.data.payload.decrypted.text | lower }}"
  action:
    - delay: "00:00:01"
    - action: meshcore.send_channel_message
      data:
        channel_idx: 6
        message: >
          {% set snr = trigger.event.data.payload.parsed.snr | default('N/A') %}
          {% set rssi = trigger.event.data.payload.parsed.rssi | default('N/A') %}
          [Test] SNR: {{ snr }}dB | RSSI: {{ rssi }}dBm. Recibido en base Montgat.
