alias: "MeshCore Bot: Resumen Diario (22:00)"
triggers:
  - trigger: time
    at: "22:00:00"
actions:
  - delay:
      seconds: 1
  - action: meshcore.send_channel_message
    data:
      channel_idx: 6
      message: >
        {% set msjs = states('input_number.mesh_mensajes_dia') | int %} {% set
        nuevos = states('input_number.mesh_nodos_nuevos_dia') | int %}

        📊 [Reporte] Tráfico hoy: {{ msjs }} mensajes. Nodos nuevos detectados:
        {{ nuevos }}. Que la propa os acompañe. 73
  - action: input_number.set_value
    target:
      entity_id:
        - input_number.mesh_mensajes_dia
        - input_number.mesh_nodos_nuevos_dia
    data:
      value: 0
mode: single
